-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Student"
(
    "OUTID" character varying(255) NOT NULL,
    "ZoneID" character varying(255),
    "SchoolID" character varying(255),
    "Birth" integer,
    "SexTypeName" character varying(255),
    "ClassLangName" character varying(255),
    "ExamYear" integer,
    PRIMARY KEY ("OUTID")
);

CREATE TABLE public."Zone"
(
    "ZoneID" character varying(255) NOT NULL,
    "RegName" character varying(255),
    "AreaName" character varying(255),
    "TerName" character varying(255),
    "TerTypeName" character varying(255),
    PRIMARY KEY ("ZoneID")
);

CREATE TABLE public."School"
(
    "SchoolID" character varying(255) NOT NULL,
    "ZoneID" character varying(255),
    "Name" character varying(255),
    "TypeName" character varying(255),
    "Parent" character varying(255),
    PRIMARY KEY ("SchoolID")
);

CREATE TABLE public."Exam"
(
    "OUTID" character varying(255) NOT NULL,
    "TestName" character varying(255),
    "SchoolID" character varying(255),
    "DPALevelID" serial,
    "TestStatus" character varying(255),
    "Ball100" numeric,
    "Ball12" numeric,
    "Ball" numeric,
    "AdaptScale" integer,
    PRIMARY KEY ("OUTID")
);

CREATE TABLE public."DPA"
(
    "DPALevelID" serial NOT NULL,
    "DPALevel" character varying(255),
    PRIMARY KEY ("DPALevelID")
);

ALTER TABLE public."Student"
    ADD FOREIGN KEY ("ZoneID")
    REFERENCES public."Zone" ("ZoneID")
    NOT VALID;


ALTER TABLE public."School"
    ADD FOREIGN KEY ("ZoneID")
    REFERENCES public."Zone" ("ZoneID")
    NOT VALID;


ALTER TABLE public."Exam"
    ADD FOREIGN KEY ("SchoolID")
    REFERENCES public."School" ("SchoolID")
    NOT VALID;


ALTER TABLE public."Exam"
    ADD FOREIGN KEY ("OUTID")
    REFERENCES public."Student" ("OUTID")
    NOT VALID;


ALTER TABLE public."Exam"
    ADD FOREIGN KEY ("DPALevelID")
    REFERENCES public."DPA" ("DPALevelID")
    NOT VALID;


ALTER TABLE public."Student"
    ADD FOREIGN KEY ("SchoolID")
    REFERENCES public."School" ("SchoolID")
    NOT VALID;

END;
